import random
import io
import os
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image

DISEASES = [
    {"name": "Apple Scab", "treatment": "Apply fungicides containing captan, mancozeb, or myclobutanil.", "pesticide": "Mancozeb 75% WP"},
    {"name": "Corn Common Rust", "treatment": "Plant resistant hybrids. Apply foliar fungicide if severe.", "pesticide": "Azoxystrobin 25% SC"},
    {"name": "Grape Black Rot", "treatment": "Remove infected mummies. Apply protective fungicides.", "pesticide": "Myclobutanil 10% WP"},
    {"name": "Potato Early Blight", "treatment": "Ensure adequate nitrogen. Apply preventative fungicides.", "pesticide": "Chlorothalonil 75% WP"},
    {"name": "Tomato Late Blight", "treatment": "Destroy infected plants immediately. Apply copper-based fungicides.", "pesticide": "Copper Oxychloride 50% WP"},
    {"name": "Healthy Crop", "treatment": "Maintain current agricultural practices. Ensure proper irrigation and nutrition.", "pesticide": "None required"}
]

# Path to the PyTorch weights (generated by train_disease_model.py)
MODEL_PATH = os.path.join(os.path.dirname(__file__), 'plant_disease_model.pth')
CLASSES_PATH = os.path.join(os.path.dirname(__file__), 'disease_classes.txt')

# ── Module-level cache so the model loads from disk only once ──
_cached_model = None
_cached_classes = None

def is_plant_leaf(image_bytes: bytes) -> bool:
    """
    Advanced Heuristic: Checks the HSV color spectrum of the image to ensure it is dominated
    by organic leaf colors (Green, Yellow, Brown) and explicitly rejects images with
    high concentrations of unnatural bright colors (Cyan, Blue, Purple, Magenta backgrounds).
    """
    try:
        img = Image.open(io.BytesIO(image_bytes))
        img = img.resize((100, 100))
        
        img_hsv = img.convert('HSV')
        
        plant_colors = 0
        unnatural_colors = 0
        
        for h, s, v in img_hsv.getdata():
            # Only count pixels that have actual color (ignore pure black/white/dark shadows)
            if s > 30 and v > 30:
                # In Pillow HSV: Hue goes from 0-255
                # 0-20 (Oranges/Reds), 20-100 (Yellows, Greens), 100-120 (Cyans)
                # 120-255 (Blues, Purples, Pinks, Magentas)
                if 10 <= h <= 100:
                    plant_colors += 1
                elif h > 120:
                    unnatural_colors += 1
                    
        total_pixels = 100 * 100
        
        # Real field photos contain overwhelming amounts of yellow/brown/green.
        has_plant_colors = (plant_colors / total_pixels) > 0.05 # Lowered heavily to allow for smaller leaves
        
        # We previously rejected images with 5% blue/purple backgrounds, but this accidentally blocked 
        # farmers holding leaves in front of their blue jeans or the sky!
        has_unnatural_background = (unnatural_colors / total_pixels) > 0.40
        
        return has_plant_colors and not has_unnatural_background
    except Exception as e:
        print(f"Error processing image: {e}")
        return False

def predict_disease(image_bytes: bytes):
    """
    Validates the image and uses a trained PyTorch CNN for prediction.
    If the model isn't trained yet, it warns the user and falls back.
    """
    if not is_plant_leaf(image_bytes):
        return {
            "name": "Invalid Image",
            "treatment": "Please upload a clear image of a plant leaf. The current image does not appear to be a crop.",
            "pesticide": "N/A"
        }
        
    # Attempt to use real inference if the model has been trained
    if os.path.exists(MODEL_PATH) and os.path.exists(CLASSES_PATH):
        try:
            global _cached_model, _cached_classes

            # Load model & classes only once, then reuse from cache
            if _cached_model is None or _cached_classes is None:
                with open(CLASSES_PATH, 'r') as f:
                    _cached_classes = [line.strip() for line in f if line.strip()]

                device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
                model = models.resnet18()
                num_ftrs = model.fc.in_features
                model.fc = nn.Linear(num_ftrs, len(_cached_classes))
                model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
                model.to(device)
                model.eval()
                _cached_model = model
                print(f"Disease model loaded: {len(_cached_classes)} classes on {device}")

            class_names = _cached_classes
            model = _cached_model
            device = next(model.parameters()).device

            # Preprocess Image — force-squash to 224x224 so the full leaf is always visible
            transform = transforms.Compose([
                transforms.Resize((224, 224)),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
            ])
            img = Image.open(io.BytesIO(image_bytes)).convert('RGB')
            input_tensor = transform(img).unsqueeze(0).to(device)

            # Inference
            with torch.no_grad():
                outputs = model(input_tensor)
                _, preds = torch.max(outputs, 1)
                predicted_class = class_names[preds[0]]

            # ── Parse class name ──────────────────────────────────────────
            # disease_classes.txt uses space-separated format: "Crop Disease"
            # e.g. "Apple Apple Scab", "Tomato Late Blight", "Potato Healthy"
            # The dataset folder names use PlantVillage "Crop___Disease" format
            # so we handle BOTH formats here.
            if "___" in predicted_class:
                # PlantVillage folder-name format: "Apple___Apple_Scab"
                parts = predicted_class.split("___")
                crop_name = parts[0].replace("_", " ").title()
                disease_name = parts[1].replace("_", " ").title()
            else:
                # Space-separated format from training: "Apple Apple Scab"
                tokens = predicted_class.split()
                crop_name = tokens[0].title() if tokens else predicted_class
                disease_name = " ".join(tokens[1:]).title() if len(tokens) > 1 else ""

            if "healthy" in disease_name.lower() or "healthy" in predicted_class.lower():
                return {
                    "name": f"Healthy {crop_name} Crop",
                    "treatment": "Your plant looks perfectly healthy! Maintain your current routine.",
                    "pesticide": "None required. Avoid unnecessary chemical applications."
                }
            else:
                return {
                    "name": f"{crop_name} - {disease_name}",
                    "treatment": f"Prune away the infected leaves immediately to prevent {disease_name} from spreading across the rest of your {crop_name} crop.",
                    "pesticide": f"Consult a local expert for {disease_name} treatments, or ask our AI Chatbot for organic remedies!"
                }

        except Exception as e:
            print(f"PyTorch Inference Error: {e}")
            pass
            
    # Fallback if no model is trained yet
    print(f"Warning: PyTorch model weights not found at {MODEL_PATH}. Returning simulation data.")
    return random.choice(DISEASES)
